### ISSUE TITLE
Installing plugin

### ISSUE THREAD

**Issue by neilloispy** [Chuxel/taco-tricks#1]
Thanks for posting this solution. 
I have been getting the "All packages for this app must use the package identity name" error. 

But I cant get this plugin to install, so these four files are to be located in a local folder and use the custom install option in VS2013? It find the folder but there is no install process. 

Could you suggest where I am going wrong.

**Comment by Chuxel** [comment]
Yes, the four files should be located in a folder, you click local, then click the "..." and select the folder. After doing that you'll click "Add."
